### ISSUE TITLE
Regression bug : Generating corrupt GLBs

### ISSUE THREAD

**Issue by noamgat** [mikedh/trimesh#1208]
Unfortunately I don't have a simple reproduction of this bug, but there is a problem that was introduced after 3.9.8, up to the time of writing this (3.9.11) where the GLBs produced by trimesh are invalid. We started seeing it today so 3.9.11 is the suspect. Has anyone else encountered this?

**Comment by mikedh** [comment]
It was probably introduced in https://github.com/mikedh/trimesh/pull/1182 which reduced file sizes a lot but was also a large change. My test cases are producing valid GLB's, is there anything unique about the scenes you're exporting? Do you have an example broken file, or maybe the output log from https://github.khronos.org/glTF-Validator/  

Thanks for the report!

**Comment by mikedh** [comment]
This is hopefully fixed by #1211 which I just released, let me know if that helps. 

The easiest way to debug corrupt GLTF headers is to turn on GLTF schema validation (requires `pip install jsonschema`), which gives an extremely thorough report on what's wrong with a file. It won't catch issues with buffers, but it does catch a lot. Validation is off by default as it's kinda slow but is on in unit tests, and you can turn it on by wrapping your export call like this:

```
trimesh.tol.strict = True
scene.export('out.glb')
trimesh.tol.strict = False
```

**Comment by noamgat** [comment]
Unfortunately it doesn't solve the problem yet. While the reproducing code is complicated, here are two outputs of the same operation. One is 3.9.8 and is correct, the other is 3.9.12 and is corrupt. Hope this helps.
[models.zip](https://github.com/mikedh/trimesh/files/6278734/models.zip)

**Comment by mikedh** [comment]
Oh got it, yeah that's in the accessor grouping logic. I'll try to push a fix sooner rather than later.

**Comment by mikedh** [comment]
Let me know if that fixes it. Should be released on PyPi shortly.

**Comment by noamgat** [comment]
Fixed!
