### ISSUE TITLE
ModuleNotFoundError: No module named 'trimesh.voxel'

### ISSUE THREAD

**Issue by oliverstefanov** [mikedh/trimesh#499]
Hi,
I just installed trimesh through conda on a new computer. My code was working fine previously but on this new install I get the following error when trying to voxelize a mesh : _ModuleNotFoundError: No module named 'trimesh.voxel'_

I checked in my conda env directory and there is indeed no "voxel" folder or file anymore, unlike the source from github. Why is it absent/removed??

Thanks

**Comment by mikedh** [comment]
In the major release this weekend (https://github.com/mikedh/trimesh/pull/467) voxel was re-written, so probably code will need to be adapted, or trimesh pinned at the last 2.x series: `pip install trimesh==2.38.39`

. Also I forgot to add it to `setup.py`, which I just fixed in https://github.com/mikedh/trimesh/commit/1fd0ff9651dc8336e6b1bb0426b88c04e361fcf4.

**Comment by oliverstefanov** [comment]
Ok i see thanks. Im simply calling the voxelized method:

`voxels = mesh.voxelized(pitch=somepitch)`
`voxels.show()`

Shouldn't it still work with the re-written voxel? Maybe the conda package still needs to be updated? 
The new voxel features seem interesting. To test them, do I have to reinstall without conda (e.g. pip)?

**Comment by mikedh** [comment]
Hey, yeah that should still work. I just merged the updated conda package, could you try with the latest?

**Comment by oliverstefanov** [comment]
Hi,

So i did  `conda update trimesh` and i still get the error:

`File "C:\Anaconda3\envs\pyoctreemesh\lib\site-packages\trimesh\base.py", line 2231, in voxelized
    from .voxel import creation
ModuleNotFoundError: No module named 'trimesh.voxel'`

**Comment by mikedh** [comment]
Hmm, I just ran a fresh install in an isolated docker image and it look OK:
```
docker run -it continuumio/miniconda3 /bin/bash
(base) root@09a4f7986c33:/# conda install -c conda-forge trimesh
(base) root@09a4f7986c33:/# python

Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import trimesh
>>> m = trimesh.creation.icosphere()
>>> 
>>> v = m.voxelized(.1)
>>> 
>>> trimesh.__version__
'3.0.11'
```

Maybe it's windows related? What does `print(trimesh.__version__)` output for you?

**Comment by oliverstefanov** [comment]
I got '3.0.9' !
I updated conda, re-ran the "conda update trimesh", but still stuck at version 3.0.9

I also get this message from conda, not sure if it could be related:

> WARNING conda.base.context:use_only_tar_bz2(632): Conda is constrained to only using the old .tar.bz2 file format because you have conda-build installed, and it is <3.18.3.  Update or remove conda-build to get smaller downloads and faster extractions.

**Comment by mikedh** [comment]
Yeah, the fix was in `3.0.10`, not sure why it isn't upgrading. What if you do a `conda remove trimesh` followed by a `conda install trimesh`?

**Comment by oliverstefanov** [comment]
This worked, I'm at version 3.0.14 now :-)
Thanks!
